spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000  # Tempo de espera para a conexão
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.springframework: INFO
